version: 2.1
jobs:
  dump:
   docker:
      - image: aarunalr/aosp-build
   steps:
      - run:
          command: |
           bash up.sh

workflows:
  version: 2.1
  cooking:
    jobs:
      - dump
