version: 2.1
jobs:
  dump:
   docker:
      - image: z4nyx/docker:latest
   steps:
      - run:
          command: |
           bash up.sh

workflows:
  version: 2.1
  cooking:
    jobs:
      - dump
